### ISSUE TITLE
Move authentication request to dedicated class

### ISSUE THREAD

**Issue by Kryniol** [xsolve-pl/salesforce-client#71]
In order to have all the requests being sent to the Salesforce API stored in unified manner we could research if it's possible to move Authenticator::getRequest() logic to separate class which would implement `RequestInterface` like all other requests.

**Comment by adrianwaler** [comment]
```php
$authenticator = new Authenticator(
    $client,
    [new PasswordGrantRegenerateStrategy()]
);
$tokenGenerator = new TokenGenerator(
    $credentials,
    $authenticator,
    new BlablacarRedisStorage(new Redis())
);

$salesforceClient = new SalesforceClient($client, $tokenGenerator, 'v37.0');
```

As you can see `Authenticator` do not have `SalesforceClient` but `HttpClient`. We need implementation of SalesforceClient which do not need TokenGenerator.

**Comment by Kryniol** [comment]
Then we'd need to extract an interface from `SalesforceClient` and introduce new "unauthenticated" implementation. I'll check if this wouldn't be overengineering :)

**Comment by Kryniol** [comment]
After some thinking, the authentication request doesn't really represent a request which could be sent to SalesforceClient, it's side HTTP request to allow sending every other request to the API. Also this request must not be manually resend with SalesforceClient by lib users and storing it along with other requests might suggest that they can freely use it for some reason.
All in all, I don't think it's good idea. Closing this one.
